# Generated by Django 4.2.3 on 2023-07-18 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.IntegerField(default=None, null=True)),
                ('current_location', models.CharField(choices=[('Abia', 'Abia (Umuahia)'), ('Adamawa', 'Adamawa (Yola)'), ('Akwa Ibom', 'Akwa Ibom (Uyo)'), ('Anambra', 'Anambra (Awka)'), ('Bauchi', 'Bauchi (Bauchi)'), ('Bayelsa', 'Bayelsa (Yenagoa)'), ('Benue', 'Benue (Makurdi)'), ('Borno', 'Borno (Maiduguri)'), ('Cross River', 'Cross River (Calabar)'), ('Delta', 'Delta (Asaba)'), ('Ebonyi', 'Ebonyi (Abakaliki)'), ('Edo', 'Edo (Benin City)'), ('Ekiti', 'Ekiti (Ado Ekiti)'), ('Enugu', 'Enugu (Enugu)'), ('Gombe', 'Gombe (Gombe)'), ('Imo', 'Imo (Owerri)'), ('Jigawa', 'Jigawa (Dutse)'), ('Kaduna', 'Kaduna (Kaduna)'), ('Kano', 'Kano (Kano)'), ('Katsina', 'Katsina (Katsina)'), ('Kebbi', 'Kebbi (Birnin Kebbi)'), ('Kogi', 'Kogi (Lokoja)'), ('Kwara', 'Kwara (Ilorin)'), ('Lagos', 'Lagos (Ikeja)'), ('Nasarawa', 'Nasarawa (Lafia)'), ('Niger', 'Niger (Minna)'), ('Ogun', 'Ogun (Abeokuta)'), ('Ondo', 'Ondo (Akure)'), ('Osun', 'Osun (Osogbo)'), ('Oyo', 'Oyo (Ibadan)'), ('Plateau', 'Plateau (Jos)'), ('Rivers', 'Rivers (Port Harcourt)'), ('Sokoto', 'Sokoto (Sokoto)'), ('Taraba', 'Taraba (Jalingo)'), ('Yobe', 'Yobe (Damaturu)'), ('Zamfara', 'Zamfara (Gusau)')], default='Abia', max_length=100)),
                ('intern_category', models.CharField(choices=[('About to graduate', 'About to graduate'), ('Just graduated', 'Just graduated'), ('Looking to change fields', 'Looking to change fields')], default='About to graduate', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_size', models.CharField(choices=[('1-50', '1-50'), ('51-100', '51-100'), ('100-1000', '100-1000'), ('1000-5000', '1000-5000'), ('<5000', '<5000')], default='Company Size', max_length=100)),
                ('established_year', models.CharField(choices=[('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018')], default='Established Year', max_length=100)),
                ('company_website', models.CharField(default='Enter Website Name', max_length=100)),
                ('company_url', models.CharField(default='Enter Websiter URL', max_length=100)),
                ('company_mission', models.TextField(default=None, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('about_us', models.CharField(choices=[('Word of mouth', 'Word of mouth'), ('Facebook', 'Facebook'), ('Linkedin', 'Linkedin'), ('Reddit', 'Reddit'), ('AD', 'AD')], default='Select', max_length=100)),
            ],
        ),
    ]
