# Generated by Django 4.2.3 on 2023-08-20 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiterprofile",
            name="company_mission",
            field=models.TextField(
                default=None,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
    ]
