# Generated by Django 4.2.3 on 2023-07-14 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_name_user_first_name_user_current_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_size', models.CharField(choices=[('1-50', '1-50'), ('51-100', '51-100'), ('100-1000', '100-1000'), ('1000-5000', '1000-5000'), ('<5000', '<5000')], default='Company Size', max_length=100)),
                ('established_year', models.CharField(choices=[('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018')], default='Established Year', max_length=100)),
                ('company_website', models.CharField(default='Enter Website Name', max_length=100)),
                ('company_url', models.CharField(default='Enter Websiter URL', max_length=100)),
                ('company_mission', models.TextField(default=None, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('about_us', models.CharField(choices=[('Word of mouth', 'Word of mouth'), ('Facebook', 'Facebook'), ('Linkedin', 'Linkedin'), ('Reddit', 'Reddit'), ('AD', 'AD')], default='Select', max_length=100)),
            ],
        ),
    ]
