# Generated by Django 4.2.3 on 2023-08-26 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_rename_roles_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internprofile",
            name="otp",
        ),
    ]
